server:
  port: 3000
  address: 0.0.0.0
  servlet:
    context-path: /administration

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/administration
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

# Logging
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        data: debug
  org:
    hibernate:
      type:
        description:
          sql: trace